[build]
command = "npm run build"
publish = "dist/spa"

[build.environment]
NODE_VERSION = "22"

[[redirects]]
from = "/api/*"
to = "https://api2.dalmiatrusts.in/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
